services:
  mt5:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mt5
    ports:
      - "3000:3000" # MetaTrader5 Web Interface
      - "8001:8001" # RPyC Server for Python MetaTrader Library
      - "5000:5000" # MT5 API
      - "18812:18812" # MT5Linux server
    volumes:
      - ./config:/config
    environment:
      CUSTOM_USER: your_username # Replace with your desired username
      PASSWORD: your_secure_password # Replace with your desired password
    restart: unless-stopped
